### ISSUE TITLE
migrations:create gives empty file

### ISSUE THREAD

**Issue by trta911** [nextras/migrations#117]
I'm install migrations by manual from your site. In my neon config I have this options:

```
extensions:
    console: Contributte\Console\DI\ConsoleExtension(%consoleMode%)
    migrations: Nextras\Migrations\Bridges\NetteDI\MigrationsExtension



migrations:
    dir: %appDir%/../migrations # migrations base directory
    driver: mysql               # pgsql or mysql
    dbal: nette               # nextras, nette, doctrine or dibi
    withDummyData: %debugMode%
```

after call 

`bin/console -vvv  migrations:create structures test`

I got in migrations folder an empty sql file. no error, no warning. Just empty file.  I also try other options (basic-data, dummy-data) with no luck (same as first). What can be wrong please?

**Comment by mabar** [comment]
That's what it is supposed to do. Command purpose is to generate file with proper name so migrations are executed in right order.

Only implemented diff generator is for Doctrine ORM. With it can be non-empty migrations generated.
```neon
migrations:
	diffGenerator: doctrine
```

**Comment by trta911** [comment]
Thank you for fast reply.

I'm fix neon (also wit help of another "howto"), so my final look is

```
parameters:
    doctrine:
        host: localhost
        user: root
        password: root
        dbname: mydatabase

extensions:
    console: Contributte\Console\DI\ConsoleExtension(%consoleMode%)
    migrations: Nextras\Migrations\Bridges\NetteDI\MigrationsExtension
    doctrine.dbal: Nettrine\DBAL\DI\DbalExtension
    doctrine.cache: Nettrine\Cache\DI\CacheExtension

migrations:
    dir: %appDir%/../migrations # migrations base directory
    driver: mysql               # pgsql or mysql
    dbal: nette               # nextras, nette, doctrine or dibi
    withDummyData: %debugMode%
    diffGenerator: doctrine
```

After that I got this error

```
Next Nette\DI\ServiceCreationException: Service 'migrations.diffGenerator.structures' (type of Nextras\Migrations\IDiffGenerator): Service of type 'Doctrine\ORM\EntityManagerInterface' not found. in /var/www/app/vendor/nette/di/src/DI/Resolver.php:436
```

So I install doctrine by 

```
 composer require nettrine/dbal
```
and what next please?  what can I install more? or do?
