### ISSUE TITLE
PostgreSQL's schema should be easier to change

### ISSUE THREAD

**Issue by JanTvrdik** [nextras/migrations#23]
Currently you need to write something like

~~~
nextras.migrations:
	dir: %appDir%/../migrations


services:
	migrationsDbal: Nextras\Migrations\Bridges\NextrasDbal\NextrasAdapter
	migrationsDriver: Nextras\Migrations\Drivers\PgSqlDriver(..., ..., my_schema)
~~~

The following unfortunately does not currently work 

~~~
nextras.migrations:
	dir: %appDir%/../migrations
	driver: Nextras\Migrations\Drivers\PgSqlDriver(..., ..., my_schema)
	dbal: nextras 
~~~

**Comment by f3l1x** [comment]
And what about 

```yaml
nextras.migrations:
    dir: %appDir%/../migrations
    driver: pgsql(..., ..., my_schema)
    dbal: nextras 
```
